/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_matao_ndk_MainActivity */

#ifndef _Included_com_matao_ndk_MainActivity
#define _Included_com_matao_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_matao_ndk_MainActivity
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_matao_ndk_MainActivity_get
  (JNIEnv *, jobject);

/*
 * Class:     com_matao_ndk_MainActivity
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_matao_ndk_MainActivity_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
